---
description: Automates creating releases PRs and tags
filter:
  topics:
    - laravel
files:
  release-drafter.yml: .github/workflows/release-drafter.yml
  release-drafter-config.yml: .github/release-drafter.yml
  release-create-pr.yml: .github/workflows/release-create-pr.yml
