name: '[Build] Draft release'

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  draft-new-release:
    uses: dbd-net/misc-repo-manager/.github/workflows/shared-release-drafter.yml@develop
    secrets: inherit
