name: [Release] Create Alpha tag
concurrency:
  group: alpha-tag
  cancel-in-progress: true

on:
  push:
    branches:
      - develop

jobs:
  create-alpha-tag:
    uses: dbd-net/misc-repo-manager/.github/workflows/shared-release-create-alpha.yml@develop
    secrets: inherit
