name: Create release pull request
concurrency:
  group: release-pr
  cancel-in-progress: true

on:
  push:
    branches:
      - develop
jobs:
  create-pr:
    uses: dbd-net/misc-repo-manager/.github/workflows/shared-release-create-pr.yml@develop
    secrets: inherit
