name: [Build] Create and deploy release

on:
  push:
    branches: [main, develop]
  workflow_dispatch: {}

jobs:
  create-unity-release:
    uses: dbd-net/misc-repo-manager/.github/workflows/shared-unity-build-game.yml@develop
    secrets: inherit
