name: [Build] Update parent repo

on:
  push:
    tags:
      - 'v?[0-9]+.**'
      - '!v?[0-9]+.**-dev**'
      - '!v?[0-9]+.**-beta**'
      - '!v?[0-9]+.**-alpha**'

jobs:
  shared-parent-updater:
    uses: dbd-net/misc-repo-manager/.github/workflows/shared-laravel-package-update-parent.yml@develop
    secrets: inherit
