name: laravel-lando
recipe: laravel
config:
  php: '7.4'
  webroot: ./public/
  via: nginx
  database: mysql:8.0
  cache: redis
env_file:
  - .lando/repman.env
services:
  appserver:
    build:
      - composer config -g repo.dbdnet composer 'https://dbdnet.repo.repman.io'
    overrides:
      environment:
        REDIS_HOST: cache
        DB_HOST: database
        DB_DATABASE: laravel
        DB_USERNAME: laravel
        DB_PASSWORD: laravel
  database:
    run_as_root:
      - "mysql -uroot -e \"CREATE DATABASE IF NOT EXISTS testing; GRANT ALL PRIVILEGES ON testing.* TO 'laravel'@'%';\""
tooling:
  phpunit:
    service: appserver
    cmd: vendor/bin/phpunit
