sonar.exclusions=tests/**/*, database/**/*, resources/**/*, config/**/*
sonar.cpd.exclusions=tests/**/*, database/**/*, resources/**/*, config/**/*
sonar.coverage.exclusions=tests/**/*, database/**/*, resources/**/*, config/**/*
