name: '[Lint] Composer'

on:
  workflow_dispatch:
  push:
    paths:
      - composer.json
      - composer.lock
    branches-ignore:
      - main

jobs:
  composer-normalize:
    uses: dbd-net/misc-repo-manager/.github/workflows/shared-composer-normalize.yml@develop
    secrets: inherit
