name: '[Lint] Pull request'

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches: [ develop ]

permissions:
  contents: read
  pull-requests: write

jobs:
  pull-request-linter:
    uses: dbd-net/misc-repo-manager/.github/workflows/shared-pull-request-linter.yml@develop
    secrets: inherit
