name: [Lint] PHP CS Fixer

on:
  push:
    paths:
      - '**.php'
    branches-ignore:
      - main

jobs:
  php-cs-fixer:
    uses: dbd-net/misc-repo-manager/.github/workflows/shared-php-cs-fixer.yml@develop
    secrets: inherit
