name: Update repository tags
on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'The repository to tag'
        required: true
        type: string
  workflow_call:
    inputs:
      repository:
        description: 'The repository to tag'
        required: true
        type: string

jobs:
  autotag:
    name: Tagging ${{ inputs.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch composer files
        continue-on-error: true
        run: |
          gh extension install mislav/gh-cp
          for F in composer.json composer.lock
          do
            gh cp '${{ github.repository_owner }}/${{ inputs.repository }}' "${F}" '${{ runner.temp }}' || {
              rm "${{ runner.temp }}/${F}"
            }
          done

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: './tasks/autotag/requirements.txt'
      - run: pip install -r ./tasks/autotag/requirements.txt

      - name: Get new labels
        id: new-labels
        working-directory: ./tasks/autotag
        run: |
          labels=$(python parse-tags.py -r '${{ inputs.repository }}' -t 'tag-mapping.json' -c '${{ runner.temp }}/composer.json')
          echo "LABELS=$(jq -cM '.names' <<< $labels)" >> "$GITHUB_OUTPUT"

      - name: Update labels
        if: steps.new-labels.outputs.LABELS != '[]'
        working-directory: ./tasks/autotag
        run: |
          labels='${{ steps.new-labels.outputs.LABELS }}'
          echo "Updating with labels: $labels"
          gh repo edit '${{ github.repository_owner }}/${{ inputs.repository }}' --add-topic $(echo $labels | jq -r '. | @csv')
