name: Automatically tag repositories
concurrency:
  group: autotag
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.REPO_PUSH_PAT }}
  REPO_LIMIT: 100

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
  push:
    paths:
      - 'tasks/autotag/*'

jobs:
  get-repos:
    name: Get the list of repos to update
    runs-on: ubuntu-latest
    outputs:
      repo-list: ${{ steps.set-repo-list.outputs.repo-list }}

    steps:
      - name: Get repostiory list
        id: set-repo-list
        run: |
          echo "::set-output name=repo-list::"$(gh search repos \
            --owner '${{ github.repository_owner }}' \
            --archived=0 \
            --language php \
            --limit ${REPO_LIMIT} \
            --sort updated \
            --include-forks false \
            --json=name)

  autotag:
    name: Update target repos
    runs-on: ubuntu-latest
    concurrency: autotag-update
    needs: 
      - get-repos
    strategy:
      matrix: 
        include: ${{ fromJson(needs.get-repos.outputs.repo-list) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Fetch composer.json
        continue-on-error: true
        run: |
          gh api 'repos/${{ github.repository_owner }}/${{ matrix.name }}/contents/composer.json' \
            -H 'Accept: application/vnd.github.VERSION.raw' \
            --jq '{name, description, keywords}' > '${{ runner.temp }}/composer.json'

      - name: Update labels
        working-directory: ./tasks/autotag
        run: |
          labels=`python parse-tags.py -r '${{ matrix.name }}' -t 'tag-mapping.json' -c '${{ runner.temp }}/composer.json'`
          echo "Updating with labels: $labels"
          echo "$labels" | gh api 'repos/${{ github.repository_owner }}/${{ matrix.name }}/topics' \
            -H 'Accept: application/vnd.github.v3+json' \
            -X PUT --input -
