name: Update dependabot automatic merging
concurrency:
  group: dependabot
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.REPO_PUSH_PAT }}
  TARGET_REPO_TAGS: laravel,debug
  REPO_LIMIT: 250

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 3 * *'
  pull_request:
    paths:
      - 'tasks/dependabot/**.yml'
  push:
    paths:
      - 'tasks/dependabot/**.yml'

jobs:
  generate-hash:
    name: Add new file hashes
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.auto-commit-changes.outputs.commit_hash }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Generate hash
        working-directory: ./tasks/dependabot
        run: |
          [ -d hashes ] || mkdir hashes
          hash=`../../bin/generate-hash.sh dependabot-auto-merge.yml dependabot.yml`
          echo "${hash}" > "hashes/${hash}.sha1"

      - name: Commit changes
        id: auto-commit-changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic update of Dependabot workflow hashes

  get-repos:
    name: Get the list of repos to update
    runs-on: ubuntu-latest
    outputs:
      repo-list: ${{ steps.set-repo-list.outputs.repo-list }}

    steps:
      - name: Get repostiory list
        id: set-repo-list
        run: |
          echo "::set-output name=repo-list::"$(gh search repos \
            --owner '${{ github.repository_owner }}' \
            --topic="${TARGET_REPO_TAGS}" \
            --archived=0 \
            --limit ${REPO_LIMIT} \
            --sort updated \
            --include-forks false \
            --json=name)

  config-update:
    name: Update target repos
    runs-on: ubuntu-latest
    needs: 
      - generate-hash
      - get-repos
    strategy:
      max-parallel: 5
      matrix:
        include: ${{ fromJson(needs.get-repos.outputs.repo-list) }}

    steps:
      - name: Checkout manager code
        uses: actions/checkout@v3
        if: ${{ needs.generate-hash.outputs.commit_hash == 0 }}
        with:
          ref: ${{ github.head_ref }}

      - name: Checkout manager code with new hash
        uses: actions/checkout@v3
        if: ${{ needs.generate-hash.outputs.commit_hash != 0 }}
        with:
          ref: ${{ needs.generate-hash.outputs.commit_hash }}

      - name: Checkout target code
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/${{ matrix.name }}
          token: '${{ secrets.REPO_PUSH_PAT }}'
          path: ./repos/${{ matrix.name }}

      - name: Property file checks
        id: hash_checks
        run: |
          found=0
          haslatest=0
          hasmatch=0
          currenthash=`./bin/generate-hash.sh ./tasks/dependabot/dependabot-auto-merge.yml ./tasks/dependabot/dependabot.yml`
          repohash=

          if [[ -f 'repos/${{ matrix.name }}/.github/dependaabot.yml' ]] && [[ -f 'repos/${{ matrix.name }}/.github/workflows/dependabot-auto-merge.yml' ]]; then
            found=1
            repohash=`./bin/generate-hash.sh ./repos/${{ matrix.name }}/dependabot-auto-merge.yml ./repos/${{ matrix.name }}/dependabot.yml`

            for filename in ./tasks/dependabot/hashes/*.sha1;
            do
              file_hash=`awk '{print $1}' "${filename}"`
              if [[ "$file_hash" == "$repohash" ]]; then
                hasmatch=1
                break
              fi
            done

            if [[ "$repohash" == "$currenthash" ]]; then
              haslatest=1
            fi
          fi

          echo ::set-output name=has-latest::$haslatest
          echo ::set-output name=has-match::$hasmatch
          echo ::set-output name=was-found::$found
          echo ::set-output name=hash-current::"$currenthash"
          echo ::set-output name=hash-remote::"$repohash"

          echo "has-latest: $haslatest"
          echo "has-match: $hasmatch"
          echo "was-found: $found"
          echo "hash-current: $currenthash"
          echo "hash-remote: $repohash"

      - name: Copy file into repository
        if: ${{ steps.hash_checks.outputs.has-latest == 0 }}
        run: |
          cp './tasks/dependabot/dependabot.yml' 'repos/${{ matrix.name }}/.github/dependabot.yml'
          cp './tasks/dependabot/dependabot-auto-merge.yml' 'repos/${{ matrix.name }}/.github/workflows/dependabot-auto-merge.yml'

      - name: Commit changes to branch
        if: ${{ steps.hash_checks.outputs.has-latest == 0 && (steps.hash_checks.outputs.has-match == 1 || steps.hash_checks.outputs.was-found == 0) }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic update of Dependabot workflows
          repository: ./repos/${{ matrix.name }}
          file_pattern: .github/dependabot.yml .github/workflows/dependabot-auto-merge.yml

      - name: Commit changes to pull request
        if: ${{ steps.hash_checks.outputs.was-found == 1 && (steps.hash_checks.outputs.has-latest == 0 && steps.hash_checks.outputs.has-match == 0) }}
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: |
            .github/dependabot.yml
            .github/workflows/dependabot-auto-merge.yml
          path: repos/${{ matrix.name }}
          token: ${{ secrets.REPO_PUSH_PAT }}
          delete-branch: true
          labels: update
          branch: update/dependabot-workflows
          commit-message: 'Update of Dependabot workflows'
          title: 'Update of Dependabot workflows'
          body: 'The upstream dependabot workflow was changed. The workflow available in this repository did not match a known hash of a previous file. Review the new changes and incorporate them if appropriate.'
