name: Update Laravel lando
concurrency:
  group: lando-laravel
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.REPO_MANAGER_PAT }}

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'tasks/lando-laravel/**.yml'
  push:
    paths:
      - 'tasks/lando-laravel/**.yml'

jobs:
  generate-hash:
    name: Add new file hashes
    uses: ./.github/workflows/add-new-hash.yml
    with:
      hash_files: lando.dist.yml repman.env
      task_dir: ./tasks/lando-laravel
      github_ref: ${{ github.head_ref }}

  get-repos:
    name: Get the list of repos to update
    uses: ./.github/workflows/get-repos.yml
    with:
      repository_owner: ${{ github.repository_owner }}
      topics: "laravel,project"
    secrets:
      access-token: ${{ secrets.REPO_MANAGER_PAT }}

  config-update:
    name: Update target repos
    runs-on: ubuntu-latest
    needs: 
      - generate-hash
      - get-repos
    strategy:
      max-parallel: 5
      matrix:
        include: ${{ fromJson(needs.get-repos.outputs.repo-list) }}

    steps:
      - name: Checkout manager code
        uses: actions/checkout@v3
        if: ${{ needs.generate-hash.outputs.commit_hash == 0 }}
        with:
          ref: ${{ github.head_ref }}

      - name: Checkout manager code with new hash
        uses: actions/checkout@v3
        if: ${{ needs.generate-hash.outputs.commit_hash != 0 }}
        with:
          ref: ${{ needs.generate-hash.outputs.commit_hash }}

      - name: Checkout target code
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/${{ matrix.name }}
          token: '${{ secrets.REPO_MANAGER_PAT }}'
          path: ./repos/${{ matrix.name }}

      - name: Property file checks
        id: hash_checks
        run: |
          currenthash=`python ./bin/generate-hash.py -- ./tasks/lando-laravel/repman.env ./tasks/lando-laravel/lando.dist.yml`
          out=`python ./bin/check-hashed-file-status.py -r '${{ matrix.name }}' -d './tasks/lando-laravel/hashes' -c "$currenthash" -- './repos/${{ matrix.name }}/.lando.dist.yml' './repos/${{ matrix.name }}/.lando/repman.env'`

          echo $out | jq

          for k in `echo $out | jq -r 'keys[]'`
          do
            v=`echo $out | jq -r ".[\"$k\"]"`
            echo "::set-output name=$k::$v"
            echo "set-output $k: $v"
          done

      - name: Copy file into repository
        if: ${{ steps.hash_checks.outputs.has-latest == 0 }}
        run: |
          [ -d './repos/${{ matrix.name }}/.lando' ] || mkdir -p './repos/${{ matrix.name }}/.lando'
          cp './tasks/lando-laravel/lando.dist.yml' './repos/${{ matrix.name }}/.lando.dist.yml'
          cp './tasks/lando-laravel/repman.env' './repos/${{ matrix.name }}/.lando/repman.env'

      - name: Commit changes to branch
        if: ${{ steps.hash_checks.outputs.has-latest == 0 && (steps.hash_checks.outputs.has-match == 1 || steps.hash_checks.outputs.was-found == 0) }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic update of Dependabot workflows
          repository: ./repos/${{ matrix.name }}
          file_pattern: .lando.dist.yml .lando/repman.env

      - name: Commit changes to pull request
        if: ${{ steps.hash_checks.outputs.was-found == 1 && (steps.hash_checks.outputs.has-latest == 0 && steps.hash_checks.outputs.has-match == 0) }}
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: |
            .lando.dist.yml
            .lando/repman.env
          path: repos/${{ matrix.name }}
          token: ${{ secrets.REPO_MANAGER_PAT }}
          delete-branch: true
          labels: update
          branch: update/dependabot-workflows
          commit-message: 'Automatic update of Dependabot workflows'
          title: 'Update of Dependabot workflows'
          body: 'The upstream dependabot workflow was changed. The workflow available in this repository did not match a known hash of a previous file. Review the new changes and incorporate them if appropriate.'
