name: Update repositories with package files
concurrency:
  group: package-files
  cancel-in-progress: true

env:
    GITHUB_TOKEN: ${{ secrets.REPO_MANAGER_PAT }}
    GH_TOKEN: ${{ secrets.REPO_MANAGER_PAT }}

on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/**'
    branches:
      - develop

jobs:
  update-outdated-repos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: gh auth setup-git

      - name: Create cache folder
        run: mkdir -p ./cache/repos

      - name: Cache repository information
        uses: actions/cache@v4
        with:
          path: ./cache/
          key: repos-and-tags

      - name: Download all repos and tags
        run: ./bin/get-repos.sh > ./cache/repos.json

      - name: Find outdated repos
        id: repo-lookup
        run: |
          ./bin/packages/get-modified-packages.sh | \
            xargs -l1 ./bin/packages/get-package-repos.sh ./cache/repos.json | \
            sort -u > ./outdated.txt
          echo "REPO_LIST=$(jq -cMRn '[inputs]' ./outdated.txt)" >> "$GITHUB_OUTPUT"

      - name: View outdated repositories
        run: |
          jq . <<< '${{ steps.repo-lookup.outputs.REPO_LIST }}'

      - name: Clone/sync repositories
        run: |
          for repository in $(jq -r '.[]' <<< '${{ steps.repo-lookup.outputs.REPO_LIST }}'); do
            ./bin/clone-or-sync.sh "${{ github.repository_owner }}" "$repository" "./cache/repos"
          done

      - name: Copy changed files
        run: |
          repositories=$(jq -r '.[]' <<< '${{ steps.repo-lookup.outputs.REPO_LIST }}')
          repo_count=$(wc -l <<< $repositories)
          current_idx=0
          for repository in $repositories; do
            current_idx=$(($current_idx+1))
            echo "::group::$repository [${current_idx}/${repo_count}]"
            for package in $(./bin/packages/get-package-intersect.sh "./cache/repos.json" "$repository"); do
              ./bin/packages/copy-modified-files.sh "$package" "./cache/repos/$repository"
            done
            echo "::endgroup::"
          done

      - name: Push changes
        run: |
          for repository in $(jq -r '.[]' <<< '${{ steps.repo-lookup.outputs.REPO_LIST }}'); do
            ./bin/git-commit.sh "./cache/repos/$repository" '[BUILD] Automatic update of managed files'
          done
