name: Update package hashes
concurrency:
  group: package-hashes
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/**'
    branches:
      - develop

jobs:
  add-new-hashes:
    name: Add or update package hashes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./bin/packages/update-package-hashes.sh
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[BUILD] Automatic update of hashes'
          commit_author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
