name: Run tests

on:
  workflow_call:

jobs:
  check-has-phpunit:
    name: Check for PHPUnit
    runs-on: ubuntu-latest
    outputs:
      found: ${{ steps.has-phpunit.outputs.hash != '' }}
    steps:
      - uses: actions/checkout@v4
      - name: Check for phpunit.xml.dist
        id: has-phpunit
        run: echo "hash=${{ hashFiles('phpunit.xml.dist') }}" >> "$GITHUB_OUTPUT"

  run-tests:
    name: Run PHPUnit
    runs-on: ubuntu-latest
    needs:
      - check-has-phpunit
    if: needs.check-has-phpunit.outputs.found == 'true'

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: laravel
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - uses: swichers/configure-laravel-nova@v1
        with:
          user: ${{ secrets.NOVA_USER }}
          token: ${{ secrets.NOVA_TOKEN }}

      - uses: swichers/configure-repman@v1
        with:
          token: ${{ secrets.REPMAN_TOKEN }}
          organization: dbdnet

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-scripts --no-progress --ignore-platform-reqs --prefer-dist --no-interaction

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/testbench package:test --parallel
        env:
          APP_ENV: local
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel
          DB_USERNAME: root
          DB_PASSWORD: root
          REDIS_HOST: 127.0.0.1
          REDIS_PORT: 6379
