name: Create release pull request
concurrency:
  group: release-pr
  cancel-in-progress: true

on:
  workflow_call:

jobs:
  check_for_automation:
    name: Check if automated
    runs-on: ubuntu-latest
    outputs:
      automated_commit: ${{ steps.build_commit.outputs.skip != '' }}
    steps:
      - uses: actions/checkout@v4
      - name: Check if needs skip
        id: build_commit
        run: |
          echo ${{ github.event.head_commit.message }}
          echo ${{ github.event.head_commit.author.username }}
          is_automated_build=${{ startsWith('[BUILD]',  github.event.head_commit.message) }}
          is_triggered_by_github=${{ endsWith('[bot]', github.event.head_commit.author.username) }}
          is_app_project=${{ startsWith('app-', github.repository) }}
          is_app_build=$is_app_project && $is_automated_build

          if [[ $is_automated_build || $is_triggered_by_github ]] && ! $is_app_build; then
            skip=true
          else
            skip=false
          fi

          echo "skip set to: $skip"
          echo "skip=$skip" >> "$GITHUB_OUTPUT"


  create_pull_request:
    name: Create release PR
    runs-on: ubuntu-latest
    if: needs.check_for_automation.outputs.automated_commit == 'false'
    needs:
      - check_for_automation
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for existing pull request
        id: find-pull-request
        uses: juliangruber/find-pull-request-action@v1
        with:
          base: main
          branch: develop

      - name: Create pull request
        if: steps.find-pull-request.outputs.number == ''
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create -B main -H develop --title '[BUILD] Merge develop to main' --body 'Automated release merge'
