name: Create new alpha tag
concurrency:
  group: alpha-tag
  cancel-in-progress: true

on:
  workflow_call:

jobs:
  check_for_automation:
    uses: ./.github/workflows/shared-is-automated-commit.yml

  taggit:
    name: Create alpha tag
    runs-on: ubuntu-latest
    if: needs.check_for_automation.outputs.is_skippable == 'false'
    needs:
      - check_for_automation
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch version history
        run: git fetch --tags

      - name: Generate pre-release version
        uses: bencatlab/autobashed-semver@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          bump-tag: true
          file-update: false
          enable-snapshot: true
          snapshot-suffix: alpha
