name: Create release pull request
concurrency:
  group: release-pr
  cancel-in-progress: true

on:
  workflow_call:

jobs:
  check_for_automation:
    uses: ./.github/workflows/shared-is-automated-commit.yml

  create_pull_request:
    name: Create release PR
    runs-on: ubuntu-latest
    if: needs.check_for_automation.outputs.is_skippable == 'false'
    needs:
      - check_for_automation
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for existing pull request
        id: find-pull-request
        uses: juliangruber/find-pull-request-action@v1
        with:
          base: main
          branch: develop

      - name: Create pull request
        if: steps.find-pull-request.outputs.number == ''
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create -B main -H develop --title '[BUILD] Merge develop to main' --body 'Automated release merge'
