name: Create hash for SonarCloud config

on:
  push:
    paths:
      - 'tasks/sonarcloud/sonarcloud.properties'

jobs:
  sonarcloud-hash:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tasks/sonarcloud

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Generate hash
        run: |
          shasum sonarcloud.properties > hashes/(shasum sonarcloud.properties | awk '{print $1}').sha1       

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add hash for new properties file